version: 2.1

orbs:
  android: circleci/android@3.2.0

jobs:
  build:
    executor:
      name: android/android_docker
      tag: 2025.03.1
    steps:
      - checkout
      - android/restore_gradle_cache
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Build
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - android/save_gradle_cache
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  build-and-test:
    jobs:
      - build